In this practice we are going to cover Python commands related with precission, and experiment with the consecuences of the computer's limited precission arithmetic.

In [7]:
import numpy as np
import matplotlib.pyplot as plt
from numpy import linalg as LA
import time

**Rounding:**

In [8]:
a = np.array([-5/3, -3/2, -1/5, 1/5, 31/20, 5/3, 2.0])
print(np.ceil(a))
print(np.floor(a))
print(np.trunc(a))
print(np.round(a,4))

[-1. -1. -0.  1.  2.  2.  2.]
[-2. -2. -1.  0.  1.  1.  2.]
[-1. -1. -0.  0.  1.  1.  2.]
[-1.6667 -1.5    -0.2     0.2     1.55    1.6667  2.    ]


In [9]:
x=np.float64(1./3.)
y=np.float32(1./3.)
print(x)
print(y)

0.3333333333333333
0.33333334


In [10]:
np.float64(3)*y # np.float32(3)*y . Compare results

1.0000000298023224

In [11]:
0*0

0

In [12]:
1/0

ZeroDivisionError: division by zero

In [ ]:
0**0         # This should be NaN

[Why 0**0=1?](https://en.wikipedia.org/wiki/Zero_to_the_power_of_zero)

In [ ]:
print(np.finfo(np.float32).eps)
print(np.finfo(float).eps)

In Python 3, the / operator performs floating-point division, the // operator performs floor division, and the ‘%’ (or modulo) operator calculates the modulo division:

In [ ]:
print('5 / 3:', 5/3)
print('5 // 3:', 5//3)
print('5 % 3:', 5%3)

**Exercise:** Use the previous commands to write a function that changes from decimal to any other base. You might also need the commands "str", "float" and "int".

The following functions shows how the rounding error accumulates when you perform operations with floating-point numbers. If we run:

In [ ]:
1+1/3-1/3

it works just fine but if we use the following function to perform the same operations several times (check what happens yourself):

In [ ]:
def add_and_subtract(iterations):
    result = 1
    
    for i in range(iterations):
        result += 1/3

    for i in range(iterations):
        result -= 1/3
    return result

**Exercise:**
* Write in a paper what the following code is doing, and calculate by hand when should it stop.
* Run the code.
* Change the code so it works as it should

In [ ]:
s = 0.0

for i in range(1000):
    s += 1.0/10.0
    if s == 1.0:
        break
print(i) 

999


**Curiosities of the floating point arithmetic:** Which is the right way to add numbers?

In [ ]:
g = 1
delta = 2**(-53);
for j in range(1,2**(20)):
    g += delta

print(g)

Do the same sum changing the order.

In [ ]:
g = 0
delta = 2**(-53);
for j in range(1,2**(20)):
    g += delta

g+= 1    

print(g)

In [ ]:
10.**np.array(np.arange(-20,1))

What has happend? Why?

## **IF POSSIBLE ADD THE NUMBERS WITH SMALLER ABSOLUTE VALUE FIRST**

$\qquad$

Another source of errors is the **truncation error**.

The term truncation error in the Taylor polynomial refers to the error involved in using a truncated, or finite, summation to approximate the sum of an infinite series.

For example, a well known Taylor series: 

$$ e^{x}=\sum _{n=0}^{\infty }{\frac {x^{n}}{n!}}=1+x+{\frac {x^{2}}{2!}}+{\frac {x^{3}}{3!}}+\cdots $$

When using a computer we can't use the whole series, and when we use the Taylor polynomial of order $n$ we are making an error.

For a general $f(x)$ we have:

$$P_n(x)=f(x_0) + f'(x_0)(x - x_0) + \frac{f''(x_0)}{2!}(x − x_0)^2 +\ldots+ \frac{f ^{(n)}(x_0)}{n!}(x − x_0)^n$$

But $P_n(x)\neq f(x)$, there is an error 

$$R_n(x) = \frac{f^{(n+1)}(ξ(x))}{(n + 1)!} (x − x_0)^{n+1}$$

**Exercise:** Approximate $\cos{(x)}$ by its Taylor polynomials of order 1,2,3,4,5. Plot the function and the approximations over the interval $[-\pi,\pi]$.

* How is the error close to 0?
* How is the error close to $\pi$?



## **More exercises:**
1. Operations in IEEE-Arithmetic don't fulfill the associative properties of the product and the sum. Example:

> $x = 1, \quad y = 2^{(-53)}, \quad z = 2^{(-53)}$

> print(x+(y+z)==(x+y)+z)

 * Give an example where the product associative property is not fulfilled in the IEEE arithmetic and explain why.
 * Give an example where the distributive property does not hold.

2. The function $f_1 (x,\delta) = \cos(x + \delta) - \cos(x)$  can be transformed into another form, $f_2 (x,\delta)$, using the trigonometric identity:

$$\cos(\phi)- cos(\varphi) =-2 \sin (\frac{\phi +\varphi}{2} ) \sin(\frac{\phi -\varphi}{2})$$

> Thus, $f_1$ and $f_2$ have the same values, in exact arithmetic, for any given argument values $x$ and $\delta$.

> Write a code that calculates $g_1(x,\delta)=f_1(x,\delta)/\delta+\sin(x)$ and $g_2(x,\delta)= f_2(x,\delta)/\delta+\sin(x)$ for $x=3$ and $\delta = 1.0e-11$. Explain the difference in the results of the two calculations.

3. The function $f_1(x_0,h)= \sin(x_0 + h)-\sin(x_0)$ can be transformed to another form, $f_2(x_0,h)$, using the trigonometric formula:

$$ \sin(\phi)- \sin(\varphi) =2 \cos(\frac{\phi +\varphi}{2} ) \sin(\frac{\phi -\varphi}{2})$$

> Thus, $f_1$ and $f_2$ have the same values, in exact arithmetic, for any pair of arguments $x$ and $h$.

> Find a formula that avoids cancellation errors for computing the approximation  to the derivative $\frac{f(x_0 + h)-f(x_0)}{h}$ of $f(x)= \sin(x)$ at $x=x_0$. 

> Write a program that implements this formula and computes an approximation of $f'(.5)$, for $h=1e-20,\cdots, 1$. For the same values of $h$, use the formula $\frac{f(x_0 + h)-f(x_0)}{h}$ to approximate the derivative and compare results.


4. Write a program that will:


*   Sum up $\frac{1}{n}$  for $n = 1,2,...,100000$. 
*   Round each number to four decimal digits, and then sum them up in five-digit decimal arithmetic for $n = 1,2,...,100000$.
*   Sum up the same rounded numbers (in four-digit decimal arithmetic) in reverse order, i.e., for $n = 100000,...,2, 1$. 

> Compare the three results and explain your observations.

5. In statistics, one often needs to compute the quantities $\bar{x}=\frac{1}{n}\sum_{i=1}^n x_i$ (average) and $s^2 = \frac{1}{n} \sum_{i=1}^n (x_i-\bar{x})^2$ (variance), where $x_1,x_2,...,x_n$, are the given data. It is easy to see that $s^2$ can also be written as $s^2=\frac{1}{n}\sum_{i=1}^{n} x_i^2-\bar{x}^2$.

* Which of the two methods to calculate $s^2$ requires fewer operations? Assume that $\bar{x}$ has already been calculated when counting the operations.
* Which of the two methods is expected to give more accurate results for $s^2$ in general?
* Write a script to check whether your answer to the previous question was correct.


# Solution

In [14]:
import numpy as np
import matplotlib.pyplot as plt
from numpy import linalg as LA
import math
import time

In [15]:
def to_base(base:int, number:int) -> str:
    """ Changes an integer from decimal base to other base. 

    Args:
        base (int): New base of the number to be converted.
        number (int): Number to be converted to the new base.

    Returns:
        str: A string representation of the number in the new base.
    """

    cociente = number // base
    remainder = number % base
    ans = str(remainder)

    while (cociente >= base):

        remainder = cociente % base
        cociente //= base
        ans = str(remainder) + ans

    else: 
        return str(cociente%base) + ans

In [16]:

print(to_base(5, 45))

140


In [17]:

s = 0.0

for i in range(1000):
    s += 1.0/10.0
    if round(s, 1) == 1.0: # Error 2 Literally compraing floats
        break

print(i) # Error 2 should be the variable s, not i
print(s)

9
0.9999999999999999


In [18]:
g = 1
delta = (2**(-53))
for j in range(1,2**(20)):
    g = math.fsum([g, delta])

print(g) # Error, g is being truncated

1.0


In [19]:
def taylor_cos(x:float, iter:int)->float:

    ans = 0

    for n in range(iter):

        coeff = (-1)**n 
        num = x**(2*n)
        dnum = math.factorial(2*n)

        ans +=  coeff*(num/dnum) 
    
    return ans

In [20]:
print(taylor_cos(math.radians(45), 5))

0.7071068056832942
